CREATE SCHEMA IF NOT EXISTS `blackjackdb` DEFAULT CHARACTER SET utf8 ;
USE `blackjackdb` ;

CREATE TABLE IF NOT EXISTS players (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    total_balance INT DEFAULT 0,
    score DOUBLE DEFAULT 0
);